# Generated by Django 5.2.2 on 2025-09-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
            ],
        ),
    ]
