# Generated by Django 5.2.2 on 2025-08-09 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=1, verbose_name='年龄')),
                ('email', models.EmailField(default='xxx@yyy.zz', max_length=254, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='书名')),
                ('pub', models.CharField(max_length=50, null=True, verbose_name='出版社')),
                ('price', models.DecimalField(decimal_places=2, default='99999', max_digits=7, verbose_name='定价')),
                ('market_price', models.DecimalField(decimal_places=2, default='99999', max_digits=7, verbose_name='零售价')),
            ],
        ),
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='无', max_length=30, verbose_name='姓名')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookstore.author')),
            ],
        ),
    ]
