# Generated by Django 5.2.2 on 2025-08-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wife',
            name='nama',
        ),
    ]
