# Generated by Django 5.2.2 on 2025-08-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_remove_wife_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='wife',
            name='name',
            field=models.CharField(default='无', max_length=30, verbose_name='姓名'),
        ),
    ]
