# Generated by Django 5.2.2 on 2025-08-15 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='出版社')),
            ],
        ),
        migrations.CreateModel(
            name='Book2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='书名')),
                ('pub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookstore2.publisher')),
            ],
        ),
    ]
