# Generated by Django 5.2.2 on 2025-07-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_remove_book_price_remove_book_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7),
        ),
    ]
