# Generated by Django 5.2.2 on 2025-07-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7),
        ),
        migrations.AddField(
            model_name='book',
            name='pub',
            field=models.CharField(default='无', max_length=50),
        ),
    ]
