# Generated by Django 5.2.2 on 2025-07-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_book_market_price_book_pub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=20)),
                ('age', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
