# Generated by Django 5.2.2 on 2025-07-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_book_pub_date_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_column='shuming', db_index=True, max_length=30),
        ),
    ]
